name = "PaStiX"
uuid = "15350434-3d5f-4982-87a9-5b6d88abd16c"
authors = ["Selmane Lebdaoui <selmane.lebdaoui@inria.fr>"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
spm = "a377bf9a-fa07-4e5f-a9da-e850a1f47d99"
